fix

diff --git a/.github/workflows/release-rc.yml b/.github/workflows/release-rc.yml
--- a/.github/workflows/release-rc.yml
+++ b/.github/workflows/release-rc.yml
@@ -30,14 +30,14 @@ jobs:
           EXISTING_TAGS=$(git tag --points-at "${{ github.sha }}")
 #          echo "$EXISTING_TAGS"
           if [ -z "$EXISTING_TAGS" ]; then
-          echo "No tags found for commit ${{ github.sha }}"
-          exit 0
+            echo "No tags found for commit ${{ github.sha }}"
+            exit 0
           fi
           for TAG in $EXISTING_TAGS; do
-          if [ "$TAG" != "${{  github.ref_name }}" ]; then
-          echo "Error: Tag $TAG already exists for commit ${{ github.sha }}"
-          exit 1
-          fi
+            if [ "$TAG" != "${{  github.ref_name }}" ]; then
+              echo "Error: Tag $TAG already exists for commit ${{ github.sha }}"
+              exit 1
+            fi
           done
           echo "No other tags found for commit ${{ github.sha }} (only ${{  github.ref_name }} exists)"
 
